/* Generated by tools/bindgen from the specs in bindings/; do not edit.
 * Every generated function rejects a NULL handle with TSC_INVALID_ARGUMENT
 * before looking at its other arguments, which are all invalid here (NULL
 * pointers, NaN, out-of-range values); the outputs are valid. A constructor
 * (no handle) rejects those invalid arguments and leaves *out NULL. */
#include "typesafe_carla/ffi.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

static int g_failures = 0;

static void expect_null_rejected(tsc_status_t status, const char *function) {
  if (status != TSC_INVALID_ARGUMENT ||
      strstr(tsc_last_error_message(), "must not be NULL") == NULL) {
    fprintf(stderr, "%s: NULL handle not rejected (status %d: %s)\n", function, (int)status,
            tsc_last_error_message());
    ++g_failures;
  }
}

static void expect_args_rejected(tsc_status_t status, const void *out, const char *function) {
  if (status != TSC_INVALID_ARGUMENT || out != NULL) {
    fprintf(stderr, "%s: invalid arguments not rejected (status %d: %s)\n", function,
            (int)status, tsc_last_error_message());
    ++g_failures;
  }
}

int main(void) {
  expect_null_rejected(tsc_actor_destroy(NULL, (int32_t[1]){0}), "tsc_actor_destroy");
  expect_null_rejected(tsc_actor_get_id(NULL, (uint32_t[1]){0}), "tsc_actor_get_id");
  expect_null_rejected(tsc_actor_get_type_id(NULL, (tsc_string_t[1]){0}), "tsc_actor_get_type_id");
  expect_null_rejected(tsc_actor_is_alive(NULL, (int32_t[1]){0}), "tsc_actor_is_alive");
  expect_null_rejected(tsc_actor_get_transform(NULL, (tsc_transform_t[1]){0}), "tsc_actor_get_transform");
  expect_null_rejected(tsc_actor_set_transform(NULL, NULL), "tsc_actor_set_transform");
  expect_null_rejected(tsc_actor_get_location(NULL, (tsc_location_t[1]){0}), "tsc_actor_get_location");
  expect_null_rejected(tsc_actor_set_location(NULL, NULL), "tsc_actor_set_location");
  expect_null_rejected(tsc_actor_get_velocity(NULL, (tsc_vector3d_t[1]){0}), "tsc_actor_get_velocity");
  expect_null_rejected(tsc_actor_set_target_velocity(NULL, NULL), "tsc_actor_set_target_velocity");
  expect_null_rejected(tsc_actor_get_acceleration(NULL, (tsc_vector3d_t[1]){0}), "tsc_actor_get_acceleration");
  expect_null_rejected(tsc_actor_get_angular_velocity(NULL, (tsc_vector3d_t[1]){0}), "tsc_actor_get_angular_velocity");
  expect_null_rejected(tsc_actor_get_bounding_box(NULL, (tsc_bounding_box_t[1]){0}), "tsc_actor_get_bounding_box");
  expect_null_rejected(tsc_actor_set_target_angular_velocity(NULL, NULL), "tsc_actor_set_target_angular_velocity");
  expect_null_rejected(tsc_actor_add_impulse(NULL, NULL), "tsc_actor_add_impulse");
  expect_null_rejected(tsc_actor_add_force(NULL, NULL), "tsc_actor_add_force");
  expect_null_rejected(tsc_actor_add_angular_impulse(NULL, NULL), "tsc_actor_add_angular_impulse");
  expect_null_rejected(tsc_actor_add_torque(NULL, NULL), "tsc_actor_add_torque");
  expect_null_rejected(tsc_actor_set_simulate_physics(NULL, 0), "tsc_actor_set_simulate_physics");
  expect_null_rejected(tsc_actor_set_enable_gravity(NULL, 0), "tsc_actor_set_enable_gravity");
  expect_null_rejected(tsc_actor_get_actor_name(NULL, (tsc_string_t[1]){0}), "tsc_actor_get_actor_name");
  expect_null_rejected(tsc_actor_get_actor_class_name(NULL, (tsc_string_t[1]){0}), "tsc_actor_get_actor_class_name");
  expect_null_rejected(tsc_actor_get_actor_state(NULL, (int32_t[1]){0}), "tsc_actor_get_actor_state");
  expect_null_rejected(tsc_actor_is_active(NULL, (int32_t[1]){0}), "tsc_actor_is_active");
  expect_null_rejected(tsc_actor_is_dormant(NULL, (int32_t[1]){0}), "tsc_actor_is_dormant");
  expect_null_rejected(tsc_actor_get_parent(NULL, (tsc_actor_t *[1]){NULL}), "tsc_actor_get_parent");
  expect_null_rejected(tsc_actor_get_semantic_tags(NULL, (uint8_t[1]){0}, 0, (size_t[1]){0}), "tsc_actor_get_semantic_tags");
  expect_null_rejected(tsc_actor_set_collisions(NULL, 0), "tsc_actor_set_collisions");
  expect_null_rejected(tsc_actor_enable_constant_velocity(NULL, NULL), "tsc_actor_enable_constant_velocity");
  expect_null_rejected(tsc_actor_disable_constant_velocity(NULL), "tsc_actor_disable_constant_velocity");
  expect_null_rejected(tsc_actor_add_force_at_location(NULL, NULL, NULL), "tsc_actor_add_force_at_location");
  expect_null_rejected(tsc_actor_add_impulse_at_location(NULL, NULL, NULL), "tsc_actor_add_impulse_at_location");
  expect_null_rejected(tsc_actor_apply_texture_color(NULL, 99, NULL), "tsc_actor_apply_texture_color");
  expect_null_rejected(tsc_actor_apply_texture_float_color(NULL, 99, NULL), "tsc_actor_apply_texture_float_color");
  expect_null_rejected(tsc_actor_get_bone_names(NULL, (tsc_string_list_t[1]){0}), "tsc_actor_get_bone_names");
  expect_null_rejected(tsc_actor_get_bone_world_transforms(NULL, (tsc_transform_list_t[1]){0}), "tsc_actor_get_bone_world_transforms");
  expect_null_rejected(tsc_actor_get_bone_relative_transforms(NULL, (tsc_transform_list_t[1]){0}), "tsc_actor_get_bone_relative_transforms");
  expect_null_rejected(tsc_actor_get_component_names(NULL, (tsc_string_list_t[1]){0}), "tsc_actor_get_component_names");
  expect_null_rejected(tsc_actor_get_component_world_transform(NULL, NULL, 1, (tsc_transform_t[1]){0}), "tsc_actor_get_component_world_transform");
  expect_null_rejected(tsc_actor_get_component_relative_transform(NULL, NULL, 1, (tsc_transform_t[1]){0}), "tsc_actor_get_component_relative_transform");
  expect_null_rejected(tsc_actor_get_socket_names(NULL, (tsc_string_list_t[1]){0}), "tsc_actor_get_socket_names");
  expect_null_rejected(tsc_actor_get_socket_world_transforms(NULL, (tsc_transform_list_t[1]){0}), "tsc_actor_get_socket_world_transforms");
  expect_null_rejected(tsc_actor_get_socket_relative_transforms(NULL, (tsc_transform_list_t[1]){0}), "tsc_actor_get_socket_relative_transforms");
  expect_null_rejected(tsc_actor_blueprint_get_id(NULL, (tsc_string_t[1]){0}), "tsc_actor_blueprint_get_id");
  expect_null_rejected(tsc_actor_blueprint_has_tag(NULL, NULL, 1, (int32_t[1]){0}), "tsc_actor_blueprint_has_tag");
  expect_null_rejected(tsc_actor_blueprint_has_attribute(NULL, NULL, 1, (int32_t[1]){0}), "tsc_actor_blueprint_has_attribute");
  expect_null_rejected(tsc_actor_list_filter(NULL, NULL, 1, (tsc_actor_list_t *[1]){NULL}), "tsc_actor_list_filter");
  expect_null_rejected(tsc_actor_blueprint_get_tags(NULL, (tsc_string_list_t[1]){0}), "tsc_actor_blueprint_get_tags");
  expect_null_rejected(tsc_actor_blueprint_match_tags(NULL, NULL, 1, (int32_t[1]){0}), "tsc_actor_blueprint_match_tags");
  expect_null_rejected(tsc_blueprint_library_filter(NULL, NULL, 1, (tsc_blueprint_library_t *[1]){NULL}), "tsc_blueprint_library_filter");
  expect_null_rejected(tsc_blueprint_library_filter_by_attribute(NULL, NULL, 1, NULL, 1, (tsc_blueprint_library_t *[1]){NULL}), "tsc_blueprint_library_filter_by_attribute");
  expect_null_rejected(tsc_client_set_timeout(NULL, NAN), "tsc_client_set_timeout");
  expect_null_rejected(tsc_client_get_timeout(NULL, (double[1]){0}), "tsc_client_get_timeout");
  expect_null_rejected(tsc_client_get_client_version(NULL, (tsc_string_t[1]){0}), "tsc_client_get_client_version");
  expect_null_rejected(tsc_client_get_server_version(NULL, (tsc_string_t[1]){0}), "tsc_client_get_server_version");
  expect_null_rejected(tsc_client_get_world(NULL, (tsc_world_t *[1]){NULL}), "tsc_client_get_world");
  expect_null_rejected(tsc_client_load_world(NULL, NULL, 1, 0, (tsc_world_t *[1]){NULL}), "tsc_client_load_world");
  expect_null_rejected(tsc_client_reload_world(NULL, 0, (tsc_world_t *[1]){NULL}), "tsc_client_reload_world");
  expect_null_rejected(tsc_client_start_recorder(NULL, NULL, 1, 0, (tsc_string_t[1]){0}), "tsc_client_start_recorder");
  expect_null_rejected(tsc_client_stop_recorder(NULL), "tsc_client_stop_recorder");
  expect_null_rejected(tsc_client_show_recorder_file_info(NULL, NULL, 1, 0, (tsc_string_t[1]){0}), "tsc_client_show_recorder_file_info");
  expect_null_rejected(tsc_client_show_recorder_collisions(NULL, NULL, 1, 0, 0, (tsc_string_t[1]){0}), "tsc_client_show_recorder_collisions");
  expect_null_rejected(tsc_client_show_recorder_actors_blocked(NULL, NULL, 1, 0, 0, (tsc_string_t[1]){0}), "tsc_client_show_recorder_actors_blocked");
  expect_null_rejected(tsc_client_replay_file(NULL, NULL, 1, 0, 0, 0, 0, (tsc_string_t[1]){0}), "tsc_client_replay_file");
  expect_null_rejected(tsc_client_stop_replayer(NULL, 0), "tsc_client_stop_replayer");
  expect_null_rejected(tsc_client_set_replayer_time_factor(NULL, NAN), "tsc_client_set_replayer_time_factor");
  expect_null_rejected(tsc_client_generate_opendrive_world(NULL, NULL, 0, NULL, 0, (tsc_world_t *[1]){NULL}), "tsc_client_generate_opendrive_world");
  expect_null_rejected(tsc_client_get_traffic_manager(NULL, 0, (tsc_traffic_manager_t *[1]){NULL}), "tsc_client_get_traffic_manager");
  expect_null_rejected(tsc_client_set_replayer_ignore_hero(NULL, 0), "tsc_client_set_replayer_ignore_hero");
  expect_null_rejected(tsc_client_set_replayer_ignore_spectator(NULL, 0), "tsc_client_set_replayer_ignore_spectator");
  expect_null_rejected(tsc_client_get_available_maps(NULL, (tsc_string_list_t[1]){0}), "tsc_client_get_available_maps");
  expect_null_rejected(tsc_client_get_required_files(NULL, NULL, 1, 0, (tsc_string_list_t[1]){0}), "tsc_client_get_required_files");
  expect_null_rejected(tsc_client_request_file(NULL, NULL, 1), "tsc_client_request_file");
  expect_null_rejected(tsc_client_set_files_base_folder(NULL, NULL, 1, (int32_t[1]){0}), "tsc_client_set_files_base_folder");
  expect_null_rejected(tsc_collision_event_get_actor(NULL, (tsc_actor_t *[1]){NULL}), "tsc_collision_event_get_actor");
  expect_null_rejected(tsc_collision_event_get_other_actor(NULL, (tsc_actor_t *[1]){NULL}), "tsc_collision_event_get_other_actor");
  expect_null_rejected(tsc_debug_draw_point(NULL, NULL, 0, NULL, NAN, 0), "tsc_debug_draw_point");
  expect_null_rejected(tsc_debug_draw_line(NULL, NULL, NULL, 0, NULL, NAN, 0), "tsc_debug_draw_line");
  expect_null_rejected(tsc_debug_draw_arrow(NULL, NULL, NULL, 0, 0, NULL, NAN, 0), "tsc_debug_draw_arrow");
  expect_null_rejected(tsc_debug_draw_box(NULL, NULL, NULL, 0, NULL, NAN, 0), "tsc_debug_draw_box");
  expect_null_rejected(tsc_debug_draw_string(NULL, NULL, NULL, 1, 0, NULL, NAN, 0), "tsc_debug_draw_string");
  expect_null_rejected(tsc_debug_clear_shapes(NULL), "tsc_debug_clear_shapes");
  expect_null_rejected(tsc_debug_clear_strings(NULL), "tsc_debug_clear_strings");
  expect_null_rejected(tsc_junction_get_id(NULL, (int32_t[1]){0}), "tsc_junction_get_id");
  expect_null_rejected(tsc_junction_get_bounding_box(NULL, (tsc_bounding_box_t[1]){0}), "tsc_junction_get_bounding_box");
  expect_null_rejected(tsc_junction_get_waypoints(NULL, 0, (tsc_waypoint_list_t *[1]){NULL}), "tsc_junction_get_waypoints");
  expect_null_rejected(tsc_landmark_get_h_offset(NULL, (double[1]){0}), "tsc_landmark_get_h_offset");
  expect_null_rejected(tsc_landmark_get_pitch(NULL, (double[1]){0}), "tsc_landmark_get_pitch");
  expect_null_rejected(tsc_landmark_get_roll(NULL, (double[1]){0}), "tsc_landmark_get_roll");
  expect_null_rejected(tsc_landmark_is_dynamic(NULL, (int32_t[1]){0}), "tsc_landmark_is_dynamic");
  expect_null_rejected(tsc_landmark_get_waypoint(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_landmark_get_waypoint");
  expect_null_rejected(tsc_landmark_get_lane_validities(NULL, (tsc_lane_validity_t[1]){0}, 0, (size_t[1]){0}), "tsc_landmark_get_lane_validities");
  expect_null_rejected(tsc_lane_invasion_event_get_actor(NULL, (tsc_actor_t *[1]){NULL}), "tsc_lane_invasion_event_get_actor");
  expect_null_rejected(tsc_lane_invasion_event_get_crossed_lane_markings(NULL, (tsc_lane_marking_t[1]){0}, 0, (size_t[1]){0}), "tsc_lane_invasion_event_get_crossed_lane_markings");
  expect_null_rejected(tsc_light_manager_get_all_lights(NULL, 99, (tsc_light_list_t[1]){0}), "tsc_light_manager_get_all_lights");
  expect_null_rejected(tsc_light_manager_get_turned_on_lights(NULL, 99, (tsc_light_list_t[1]){0}), "tsc_light_manager_get_turned_on_lights");
  expect_null_rejected(tsc_light_manager_get_turned_off_lights(NULL, 99, (tsc_light_list_t[1]){0}), "tsc_light_manager_get_turned_off_lights");
  expect_null_rejected(tsc_light_manager_set_day_night_cycle(NULL, 0), "tsc_light_manager_set_day_night_cycle");
  {
    tsc_map_t *out = (tsc_map_t *)&g_failures;
    tsc_status_t status = tsc_map_new_from_opendrive(NULL, 1, NULL, 1, &out);
    expect_args_rejected(status, out, "tsc_map_new_from_opendrive");
  }
  expect_null_rejected(tsc_map_get_name(NULL, (tsc_string_t[1]){0}), "tsc_map_get_name");
  expect_null_rejected(tsc_map_to_opendrive(NULL, (tsc_string_t[1]){0}), "tsc_map_to_opendrive");
  expect_null_rejected(tsc_map_get_spawn_points(NULL, (tsc_transform_t[1]){0}, 0, (size_t[1]){0}), "tsc_map_get_spawn_points");
  expect_null_rejected(tsc_map_get_waypoint(NULL, NULL, 0, 0, (tsc_waypoint_t *[1]){NULL}), "tsc_map_get_waypoint");
  expect_null_rejected(tsc_map_generate_waypoints(NULL, NAN, (tsc_waypoint_list_t *[1]){NULL}), "tsc_map_generate_waypoints");
  expect_null_rejected(tsc_map_get_topology(NULL, (tsc_waypoint_list_t *[1]){NULL}), "tsc_map_get_topology");
  expect_null_rejected(tsc_map_get_crosswalks(NULL, (tsc_location_t[1]){0}, 0, (size_t[1]){0}), "tsc_map_get_crosswalks");
  expect_null_rejected(tsc_map_get_all_landmarks(NULL, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_all_landmarks");
  expect_null_rejected(tsc_map_get_landmarks_of_type(NULL, NULL, 1, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_landmarks_of_type");
  expect_null_rejected(tsc_map_get_georeference(NULL, (tsc_geo_location_t[1]){0}), "tsc_map_get_georeference");
  expect_null_rejected(tsc_map_get_waypoint_xodr(NULL, 0, 0, NAN, (tsc_waypoint_t *[1]){NULL}), "tsc_map_get_waypoint_xodr");
  expect_null_rejected(tsc_map_get_landmarks_from_id(NULL, NULL, 1, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_landmarks_from_id");
  expect_null_rejected(tsc_map_get_landmark_group(NULL, NULL, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_landmark_group");
  expect_null_rejected(tsc_map_cook_in_memory_map(NULL, NULL, 1), "tsc_map_cook_in_memory_map");
  expect_null_rejected(tsc_obstacle_detection_get_distance(NULL, (double[1]){0}), "tsc_obstacle_detection_get_distance");
  expect_null_rejected(tsc_obstacle_detection_get_actor(NULL, (tsc_actor_t *[1]){NULL}), "tsc_obstacle_detection_get_actor");
  expect_null_rejected(tsc_obstacle_detection_get_other_actor(NULL, (tsc_actor_t *[1]){NULL}), "tsc_obstacle_detection_get_other_actor");
  expect_null_rejected(tsc_sensor_is_listening(NULL, (int32_t[1]){0}), "tsc_sensor_is_listening");
  expect_null_rejected(tsc_traffic_light_set_state(NULL, 99), "tsc_traffic_light_set_state");
  expect_null_rejected(tsc_traffic_light_set_green_time(NULL, NAN), "tsc_traffic_light_set_green_time");
  expect_null_rejected(tsc_traffic_light_set_yellow_time(NULL, NAN), "tsc_traffic_light_set_yellow_time");
  expect_null_rejected(tsc_traffic_light_set_red_time(NULL, NAN), "tsc_traffic_light_set_red_time");
  expect_null_rejected(tsc_traffic_light_freeze(NULL, 0), "tsc_traffic_light_freeze");
  expect_null_rejected(tsc_traffic_light_reset_group(NULL), "tsc_traffic_light_reset_group");
  expect_null_rejected(tsc_traffic_light_get_opendrive_id(NULL, (tsc_string_t[1]){0}), "tsc_traffic_light_get_opendrive_id");
  expect_null_rejected(tsc_traffic_light_get_trigger_volume(NULL, (tsc_bounding_box_t[1]){0}), "tsc_traffic_light_get_trigger_volume");
  expect_null_rejected(tsc_traffic_light_get_light_boxes(NULL, (tsc_bounding_box_t[1]){0}, 0, (size_t[1]){0}), "tsc_traffic_light_get_light_boxes");
  expect_null_rejected(tsc_traffic_light_get_affected_lane_waypoints(NULL, (tsc_waypoint_list_t *[1]){NULL}), "tsc_traffic_light_get_affected_lane_waypoints");
  expect_null_rejected(tsc_traffic_light_get_stop_waypoints(NULL, (tsc_waypoint_list_t *[1]){NULL}), "tsc_traffic_light_get_stop_waypoints");
  expect_null_rejected(tsc_traffic_light_get_group_traffic_lights(NULL, (tsc_traffic_light_list_t *[1]){NULL}), "tsc_traffic_light_get_group_traffic_lights");
  expect_null_rejected(tsc_traffic_manager_get_port(NULL, (uint16_t[1]){0}), "tsc_traffic_manager_get_port");
  expect_null_rejected(tsc_traffic_manager_set_synchronous_mode(NULL, 0), "tsc_traffic_manager_set_synchronous_mode");
  expect_null_rejected(tsc_traffic_manager_set_random_device_seed(NULL, 0), "tsc_traffic_manager_set_random_device_seed");
  expect_null_rejected(tsc_traffic_manager_set_hybrid_physics_mode(NULL, 0), "tsc_traffic_manager_set_hybrid_physics_mode");
  expect_null_rejected(tsc_traffic_manager_set_global_percentage_speed_difference(NULL, NAN), "tsc_traffic_manager_set_global_percentage_speed_difference");
  expect_null_rejected(tsc_traffic_manager_set_global_distance_to_leading_vehicle(NULL, NAN), "tsc_traffic_manager_set_global_distance_to_leading_vehicle");
  expect_null_rejected(tsc_traffic_manager_set_auto_lane_change(NULL, NULL, 0), "tsc_traffic_manager_set_auto_lane_change");
  expect_null_rejected(tsc_traffic_manager_force_lane_change(NULL, NULL, 0), "tsc_traffic_manager_force_lane_change");
  expect_null_rejected(tsc_traffic_manager_set_update_vehicle_lights(NULL, NULL, 0), "tsc_traffic_manager_set_update_vehicle_lights");
  expect_null_rejected(tsc_traffic_manager_set_osm_mode(NULL, 0), "tsc_traffic_manager_set_osm_mode");
  expect_null_rejected(tsc_traffic_manager_set_respawn_dormant_vehicles(NULL, 0), "tsc_traffic_manager_set_respawn_dormant_vehicles");
  expect_null_rejected(tsc_traffic_manager_set_boundaries_respawn_dormant_vehicles(NULL, NAN, NAN), "tsc_traffic_manager_set_boundaries_respawn_dormant_vehicles");
  expect_null_rejected(tsc_traffic_manager_set_hybrid_physics_radius(NULL, NAN), "tsc_traffic_manager_set_hybrid_physics_radius");
  expect_null_rejected(tsc_traffic_manager_set_global_lane_offset(NULL, NAN), "tsc_traffic_manager_set_global_lane_offset");
  expect_null_rejected(tsc_traffic_manager_set_collision_detection(NULL, NULL, NULL, 0), "tsc_traffic_manager_set_collision_detection");
  expect_null_rejected(tsc_traffic_manager_shut_down(NULL), "tsc_traffic_manager_shut_down");
  expect_null_rejected(tsc_traffic_manager_set_global_large_vehicle_wide_turn(NULL, 0), "tsc_traffic_manager_set_global_large_vehicle_wide_turn");
  expect_null_rejected(tsc_traffic_manager_set_large_vehicle_wide_turn(NULL, NULL, 0), "tsc_traffic_manager_set_large_vehicle_wide_turn");
  expect_null_rejected(tsc_traffic_manager_set_path(NULL, NULL, NULL, 1, 0), "tsc_traffic_manager_set_path");
  expect_null_rejected(tsc_traffic_manager_set_route(NULL, NULL, NULL, 1, 0), "tsc_traffic_manager_set_route");
  expect_null_rejected(tsc_traffic_sign_get_trigger_volume(NULL, (tsc_bounding_box_t[1]){0}), "tsc_traffic_sign_get_trigger_volume");
  expect_null_rejected(tsc_transform_get_matrix(NULL, (double[1]){0}), "tsc_transform_get_matrix");
  expect_null_rejected(tsc_transform_get_inverse_matrix(NULL, (double[1]){0}), "tsc_transform_get_inverse_matrix");
  expect_null_rejected(tsc_vehicle_apply_control(NULL, NULL), "tsc_vehicle_apply_control");
  expect_null_rejected(tsc_vehicle_get_control(NULL, (tsc_vehicle_control_t[1]){0}), "tsc_vehicle_get_control");
  expect_null_rejected(tsc_vehicle_get_physics_control(NULL, (tsc_physics_control_t *[1]){NULL}), "tsc_vehicle_get_physics_control");
  expect_null_rejected(tsc_vehicle_get_traffic_light(NULL, (tsc_traffic_light_t *[1]){NULL}), "tsc_vehicle_get_traffic_light");
  expect_null_rejected(tsc_vehicle_set_autopilot(NULL, 0, 0), "tsc_vehicle_set_autopilot");
  expect_null_rejected(tsc_vehicle_set_light_state(NULL, 0), "tsc_vehicle_set_light_state");
  expect_null_rejected(tsc_vehicle_get_light_state(NULL, (uint32_t[1]){0}), "tsc_vehicle_get_light_state");
  expect_null_rejected(tsc_vehicle_get_speed_limit(NULL, (double[1]){0}), "tsc_vehicle_get_speed_limit");
  expect_null_rejected(tsc_vehicle_get_traffic_light_state(NULL, (int32_t[1]){0}), "tsc_vehicle_get_traffic_light_state");
  expect_null_rejected(tsc_vehicle_is_at_traffic_light(NULL, (int32_t[1]){0}), "tsc_vehicle_is_at_traffic_light");
  expect_null_rejected(tsc_vehicle_apply_ackermann_control(NULL, NULL), "tsc_vehicle_apply_ackermann_control");
  expect_null_rejected(tsc_vehicle_get_ackermann_controller_settings(NULL, (tsc_ackermann_controller_settings_t[1]){0}), "tsc_vehicle_get_ackermann_controller_settings");
  expect_null_rejected(tsc_vehicle_apply_ackermann_controller_settings(NULL, NULL), "tsc_vehicle_apply_ackermann_controller_settings");
  expect_null_rejected(tsc_vehicle_open_door(NULL, 99), "tsc_vehicle_open_door");
  expect_null_rejected(tsc_vehicle_close_door(NULL, 99), "tsc_vehicle_close_door");
  expect_null_rejected(tsc_vehicle_get_failure_state(NULL, (int32_t[1]){0}), "tsc_vehicle_get_failure_state");
  expect_null_rejected(tsc_vehicle_show_debug_telemetry(NULL, 0), "tsc_vehicle_show_debug_telemetry");
  expect_null_rejected(tsc_vehicle_get_wheel_steer_angle(NULL, 99, (double[1]){0}), "tsc_vehicle_get_wheel_steer_angle");
  expect_null_rejected(tsc_vehicle_set_wheel_steer_direction(NULL, 99, NAN), "tsc_vehicle_set_wheel_steer_direction");
  expect_null_rejected(tsc_vehicle_use_carsim_road(NULL, 0), "tsc_vehicle_use_carsim_road");
  expect_null_rejected(tsc_vehicle_enable_carsim(NULL, NULL, 1), "tsc_vehicle_enable_carsim");
  expect_null_rejected(tsc_vehicle_enable_chrono_physics(NULL, 0, NAN, NULL, 1, NULL, 1, NULL, 1, NULL, 1), "tsc_vehicle_enable_chrono_physics");
  expect_null_rejected(tsc_vehicle_get_vehicle_bone_world_transforms(NULL, (tsc_transform_t[1]){0}, 0, (size_t[1]){0}), "tsc_vehicle_get_vehicle_bone_world_transforms");
  expect_null_rejected(tsc_walker_apply_control(NULL, NULL), "tsc_walker_apply_control");
  expect_null_rejected(tsc_walker_get_control(NULL, (tsc_walker_control_t[1]){0}), "tsc_walker_get_control");
  expect_null_rejected(tsc_walker_set_bones(NULL, NULL, 1), "tsc_walker_set_bones");
  expect_null_rejected(tsc_walker_get_bones(NULL, (tsc_bone_list_t *[1]){NULL}), "tsc_walker_get_bones");
  expect_null_rejected(tsc_walker_blend_pose(NULL, NAN), "tsc_walker_blend_pose");
  expect_null_rejected(tsc_walker_show_pose(NULL), "tsc_walker_show_pose");
  expect_null_rejected(tsc_walker_hide_pose(NULL), "tsc_walker_hide_pose");
  expect_null_rejected(tsc_walker_get_pose_from_animation(NULL), "tsc_walker_get_pose_from_animation");
  expect_null_rejected(tsc_walker_ai_controller_start(NULL), "tsc_walker_ai_controller_start");
  expect_null_rejected(tsc_walker_ai_controller_stop(NULL), "tsc_walker_ai_controller_stop");
  expect_null_rejected(tsc_walker_ai_controller_go_to_location(NULL, NULL), "tsc_walker_ai_controller_go_to_location");
  expect_null_rejected(tsc_walker_ai_controller_set_max_speed(NULL, NAN), "tsc_walker_ai_controller_set_max_speed");
  expect_null_rejected(tsc_waypoint_next(NULL, NAN, (tsc_waypoint_list_t *[1]){NULL}), "tsc_waypoint_next");
  expect_null_rejected(tsc_waypoint_previous(NULL, NAN, (tsc_waypoint_list_t *[1]){NULL}), "tsc_waypoint_previous");
  expect_null_rejected(tsc_waypoint_next_until_lane_end(NULL, NAN, (tsc_waypoint_list_t *[1]){NULL}), "tsc_waypoint_next_until_lane_end");
  expect_null_rejected(tsc_waypoint_previous_until_lane_start(NULL, NAN, (tsc_waypoint_list_t *[1]){NULL}), "tsc_waypoint_previous_until_lane_start");
  expect_null_rejected(tsc_waypoint_get_junction(NULL, (tsc_junction_t *[1]){NULL}), "tsc_waypoint_get_junction");
  expect_null_rejected(tsc_waypoint_get_left_lane(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_waypoint_get_left_lane");
  expect_null_rejected(tsc_waypoint_get_right_lane(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_waypoint_get_right_lane");
  expect_null_rejected(tsc_waypoint_is_rht(NULL, (int32_t[1]){0}), "tsc_waypoint_is_rht");
  expect_null_rejected(tsc_waypoint_get_left_lane_marking(NULL, (int32_t[1]){0}, (tsc_lane_marking_t[1]){0}), "tsc_waypoint_get_left_lane_marking");
  expect_null_rejected(tsc_waypoint_get_right_lane_marking(NULL, (int32_t[1]){0}, (tsc_lane_marking_t[1]){0}), "tsc_waypoint_get_right_lane_marking");
  expect_null_rejected(tsc_waypoint_get_lane_change(NULL, (int32_t[1]){0}), "tsc_waypoint_get_lane_change");
  expect_null_rejected(tsc_waypoint_get_landmarks(NULL, NAN, 0, (tsc_landmark_list_t *[1]){NULL}), "tsc_waypoint_get_landmarks");
  expect_null_rejected(tsc_waypoint_get_landmarks_of_type(NULL, NAN, NULL, 1, 0, (tsc_landmark_list_t *[1]){NULL}), "tsc_waypoint_get_landmarks_of_type");
  expect_null_rejected(tsc_world_get_id(NULL, (uint64_t[1]){0}), "tsc_world_get_id");
  expect_null_rejected(tsc_world_get_actors(NULL, (tsc_actor_list_t *[1]){NULL}), "tsc_world_get_actors");
  expect_null_rejected(tsc_world_get_actors_by_id(NULL, NULL, 1, (tsc_actor_list_t *[1]){NULL}), "tsc_world_get_actors_by_id");
  expect_null_rejected(tsc_world_get_blueprint_library(NULL, (tsc_blueprint_library_t *[1]){NULL}), "tsc_world_get_blueprint_library");
  expect_null_rejected(tsc_world_spawn_actor(NULL, NULL, NULL, NULL, (tsc_actor_t *[1]){NULL}), "tsc_world_spawn_actor");
  expect_null_rejected(tsc_world_try_spawn_actor(NULL, NULL, NULL, NULL, (tsc_actor_t *[1]){NULL}), "tsc_world_try_spawn_actor");
  expect_null_rejected(tsc_world_tick(NULL, NAN, (uint64_t[1]){0}), "tsc_world_tick");
  expect_null_rejected(tsc_world_get_snapshot(NULL, (tsc_world_snapshot_t *[1]){NULL}), "tsc_world_get_snapshot");
  expect_null_rejected(tsc_world_wait_for_tick(NULL, NAN, (tsc_world_snapshot_t *[1]){NULL}), "tsc_world_wait_for_tick");
  expect_null_rejected(tsc_world_get_map(NULL, (tsc_map_t *[1]){NULL}), "tsc_world_get_map");
  expect_null_rejected(tsc_world_get_random_location_from_navigation(NULL, (tsc_location_t[1]){0}, (int32_t[1]){0}), "tsc_world_get_random_location_from_navigation");
  expect_null_rejected(tsc_world_get_weather(NULL, (tsc_weather_t[1]){0}), "tsc_world_get_weather");
  expect_null_rejected(tsc_world_set_weather(NULL, NULL), "tsc_world_set_weather");
  expect_null_rejected(tsc_world_is_weather_enabled(NULL, (int32_t[1]){0}), "tsc_world_is_weather_enabled");
  expect_null_rejected(tsc_world_get_spectator(NULL, (tsc_actor_t *[1]){NULL}), "tsc_world_get_spectator");
  expect_null_rejected(tsc_world_get_traffic_light_from_opendrive_id(NULL, NULL, 1, (tsc_traffic_light_t *[1]){NULL}), "tsc_world_get_traffic_light_from_opendrive_id");
  expect_null_rejected(tsc_world_get_traffic_sign(NULL, NULL, (tsc_actor_t *[1]){NULL}), "tsc_world_get_traffic_sign");
  expect_null_rejected(tsc_world_get_traffic_light(NULL, NULL, (tsc_traffic_light_t *[1]){NULL}), "tsc_world_get_traffic_light");
  expect_null_rejected(tsc_world_get_traffic_lights_from_waypoint(NULL, NULL, NAN, (tsc_traffic_light_list_t *[1]){NULL}), "tsc_world_get_traffic_lights_from_waypoint");
  expect_null_rejected(tsc_world_get_traffic_lights_in_junction(NULL, 0, (tsc_traffic_light_list_t *[1]){NULL}), "tsc_world_get_traffic_lights_in_junction");
  expect_null_rejected(tsc_world_freeze_all_traffic_lights(NULL, 0), "tsc_world_freeze_all_traffic_lights");
  expect_null_rejected(tsc_world_reset_all_traffic_lights(NULL), "tsc_world_reset_all_traffic_lights");
  expect_null_rejected(tsc_world_get_vehicles_light_states(NULL, (tsc_vehicle_light_state_list_t[1]){0}), "tsc_world_get_vehicles_light_states");
  expect_null_rejected(tsc_world_get_level_bbs(NULL, 999, (tsc_bounding_box_list_t[1]){0}), "tsc_world_get_level_bbs");
  expect_null_rejected(tsc_world_get_environment_objects(NULL, 999, (tsc_environment_object_list_t[1]){0}), "tsc_world_get_environment_objects");
  expect_null_rejected(tsc_world_enable_environment_objects(NULL, NULL, 1, 0), "tsc_world_enable_environment_objects");
  expect_null_rejected(tsc_world_get_names_of_all_objects(NULL, (tsc_string_list_t[1]){0}), "tsc_world_get_names_of_all_objects");
  expect_null_rejected(tsc_world_cast_ray(NULL, NULL, NULL, (tsc_labelled_point_list_t[1]){0}), "tsc_world_cast_ray");
  expect_null_rejected(tsc_world_project_point(NULL, NULL, NULL, NAN, (int32_t[1]){0}, (tsc_labelled_point_t[1]){0}), "tsc_world_project_point");
  expect_null_rejected(tsc_world_ground_projection(NULL, NULL, NAN, (int32_t[1]){0}, (tsc_labelled_point_t[1]){0}), "tsc_world_ground_projection");
  expect_null_rejected(tsc_world_load_map_layer(NULL, 0), "tsc_world_load_map_layer");
  expect_null_rejected(tsc_world_unload_map_layer(NULL, 0), "tsc_world_unload_map_layer");
  expect_null_rejected(tsc_world_set_pedestrians_seed(NULL, 0), "tsc_world_set_pedestrians_seed");
  expect_null_rejected(tsc_world_set_pedestrians_cross_factor(NULL, NAN), "tsc_world_set_pedestrians_cross_factor");
  expect_null_rejected(tsc_world_get_imu_sensor_gravity(NULL, (double[1]){0}), "tsc_world_get_imu_sensor_gravity");
  expect_null_rejected(tsc_world_set_imu_sensor_gravity(NULL, NAN), "tsc_world_set_imu_sensor_gravity");
  expect_null_rejected(tsc_world_apply_color_texture_to_objects(NULL, NULL, 1, 99, NULL), "tsc_world_apply_color_texture_to_objects");
  expect_null_rejected(tsc_world_apply_float_color_texture_to_objects(NULL, NULL, 1, 99, NULL), "tsc_world_apply_float_color_texture_to_objects");
  expect_null_rejected(tsc_world_apply_textures_to_objects(NULL, NULL, 1, NULL, NULL, NULL, NULL), "tsc_world_apply_textures_to_objects");
  expect_null_rejected(tsc_world_get_light_manager(NULL, (tsc_light_manager_t *[1]){NULL}), "tsc_world_get_light_manager");
  expect_null_rejected(tsc_world_snapshot_get_id(NULL, (uint64_t[1]){0}), "tsc_world_snapshot_get_id");
  expect_null_rejected(tsc_world_snapshot_get_timestamp(NULL, (tsc_timestamp_t[1]){0}), "tsc_world_snapshot_get_timestamp");
  if (tsc_actor_list_size(NULL) != 0) { fputs("tsc_actor_list_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_actor_list_get(NULL, 0, (tsc_actor_t *[1]){NULL}), "tsc_actor_list_get");
  if (tsc_blueprint_library_size(NULL) != 0) { fputs("tsc_blueprint_library_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_blueprint_library_get(NULL, 0, (tsc_actor_blueprint_t *[1]){NULL}), "tsc_blueprint_library_get");
  if (tsc_bone_list_size(NULL) != 0) { fputs("tsc_bone_list_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_bone_list_get(NULL, 0, (tsc_bone_transform_out_t[1]){0}), "tsc_bone_list_get");
  if (tsc_landmark_list_size(NULL) != 0) { fputs("tsc_landmark_list_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_landmark_list_get(NULL, 0, (tsc_landmark_t[1]){0}), "tsc_landmark_list_get");
  expect_null_rejected(tsc_landmark_list_get_landmark(NULL, 0, (tsc_landmark_handle_t *[1]){NULL}), "tsc_landmark_list_get_landmark");
  if (tsc_traffic_light_list_size(NULL) != 0) { fputs("tsc_traffic_light_list_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_traffic_light_list_get(NULL, 0, (tsc_traffic_light_t *[1]){NULL}), "tsc_traffic_light_list_get");
  if (tsc_waypoint_list_size(NULL) != 0) { fputs("tsc_waypoint_list_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_waypoint_list_get(NULL, 0, (tsc_waypoint_t *[1]){NULL}), "tsc_waypoint_list_get");
  if (tsc_world_snapshot_size(NULL) != 0) { fputs("tsc_world_snapshot_size(NULL)\n", stderr); ++g_failures; }
  expect_null_rejected(tsc_world_snapshot_get(NULL, 0, (tsc_actor_snapshot_t[1]){0}), "tsc_world_snapshot_get");
  if (g_failures != 0) return 1;
  printf("test_generated: 257 generated functions reject NULL handles\n");
  return 0;
}
