/* Generated by tools/bindgen from the specs in bindings/; do not edit.
 * Every generated function rejects a NULL handle with TSC_INVALID_ARGUMENT
 * before looking at its other arguments, which are all invalid here (NULL
 * pointers, NaN, out-of-range values). */
#include "typesafe_carla/ffi.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

static int g_failures = 0;

static void expect_null_rejected(tsc_status_t status, const char *function) {
  if (status != TSC_INVALID_ARGUMENT ||
      strstr(tsc_last_error_message(), "must not be NULL") == NULL) {
    fprintf(stderr, "%s: NULL handle not rejected (status %d: %s)\n", function, (int)status,
            tsc_last_error_message());
    ++g_failures;
  }
}

int main(void) {
  expect_null_rejected(tsc_actor_get_id(NULL, NULL), "tsc_actor_get_id");
  expect_null_rejected(tsc_actor_get_type_id(NULL, NULL), "tsc_actor_get_type_id");
  expect_null_rejected(tsc_actor_is_alive(NULL, NULL), "tsc_actor_is_alive");
  expect_null_rejected(tsc_actor_get_transform(NULL, NULL), "tsc_actor_get_transform");
  expect_null_rejected(tsc_actor_set_transform(NULL, NULL), "tsc_actor_set_transform");
  expect_null_rejected(tsc_actor_get_location(NULL, NULL), "tsc_actor_get_location");
  expect_null_rejected(tsc_actor_set_location(NULL, NULL), "tsc_actor_set_location");
  expect_null_rejected(tsc_actor_get_velocity(NULL, NULL), "tsc_actor_get_velocity");
  expect_null_rejected(tsc_actor_set_target_velocity(NULL, NULL), "tsc_actor_set_target_velocity");
  expect_null_rejected(tsc_actor_get_acceleration(NULL, NULL), "tsc_actor_get_acceleration");
  expect_null_rejected(tsc_actor_get_angular_velocity(NULL, NULL), "tsc_actor_get_angular_velocity");
  expect_null_rejected(tsc_actor_get_bounding_box(NULL, NULL), "tsc_actor_get_bounding_box");
  expect_null_rejected(tsc_actor_set_target_angular_velocity(NULL, NULL), "tsc_actor_set_target_angular_velocity");
  expect_null_rejected(tsc_actor_add_impulse(NULL, NULL), "tsc_actor_add_impulse");
  expect_null_rejected(tsc_actor_add_force(NULL, NULL), "tsc_actor_add_force");
  expect_null_rejected(tsc_actor_add_angular_impulse(NULL, NULL), "tsc_actor_add_angular_impulse");
  expect_null_rejected(tsc_actor_add_torque(NULL, NULL), "tsc_actor_add_torque");
  expect_null_rejected(tsc_actor_set_simulate_physics(NULL, 0), "tsc_actor_set_simulate_physics");
  expect_null_rejected(tsc_actor_set_enable_gravity(NULL, 0), "tsc_actor_set_enable_gravity");
  expect_null_rejected(tsc_landmark_get_h_offset(NULL, NULL), "tsc_landmark_get_h_offset");
  expect_null_rejected(tsc_landmark_get_pitch(NULL, NULL), "tsc_landmark_get_pitch");
  expect_null_rejected(tsc_landmark_get_roll(NULL, NULL), "tsc_landmark_get_roll");
  expect_null_rejected(tsc_landmark_is_dynamic(NULL, NULL), "tsc_landmark_is_dynamic");
  expect_null_rejected(tsc_landmark_get_waypoint(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_landmark_get_waypoint");
  expect_null_rejected(tsc_landmark_get_lane_validities(NULL, NULL, 0, NULL), "tsc_landmark_get_lane_validities");
  expect_null_rejected(tsc_map_get_georeference(NULL, NULL), "tsc_map_get_georeference");
  expect_null_rejected(tsc_map_get_waypoint_xodr(NULL, 0, 0, NAN, (tsc_waypoint_t *[1]){NULL}), "tsc_map_get_waypoint_xodr");
  expect_null_rejected(tsc_map_get_landmarks_from_id(NULL, NULL, 1, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_landmarks_from_id");
  expect_null_rejected(tsc_map_get_landmark_group(NULL, NULL, (tsc_landmark_list_t *[1]){NULL}), "tsc_map_get_landmark_group");
  expect_null_rejected(tsc_map_cook_in_memory_map(NULL, NULL, 1), "tsc_map_cook_in_memory_map");
  expect_null_rejected(tsc_traffic_light_set_state(NULL, 99), "tsc_traffic_light_set_state");
  expect_null_rejected(tsc_traffic_light_set_green_time(NULL, NAN), "tsc_traffic_light_set_green_time");
  expect_null_rejected(tsc_traffic_light_set_yellow_time(NULL, NAN), "tsc_traffic_light_set_yellow_time");
  expect_null_rejected(tsc_traffic_light_set_red_time(NULL, NAN), "tsc_traffic_light_set_red_time");
  expect_null_rejected(tsc_traffic_light_freeze(NULL, 0), "tsc_traffic_light_freeze");
  expect_null_rejected(tsc_traffic_light_reset_group(NULL), "tsc_traffic_light_reset_group");
  expect_null_rejected(tsc_traffic_light_get_opendrive_id(NULL, NULL), "tsc_traffic_light_get_opendrive_id");
  expect_null_rejected(tsc_traffic_light_get_trigger_volume(NULL, NULL), "tsc_traffic_light_get_trigger_volume");
  expect_null_rejected(tsc_traffic_light_get_light_boxes(NULL, NULL, 0, NULL), "tsc_traffic_light_get_light_boxes");
  expect_null_rejected(tsc_traffic_light_get_affected_lane_waypoints(NULL, (tsc_waypoint_list_t *[1]){NULL}), "tsc_traffic_light_get_affected_lane_waypoints");
  expect_null_rejected(tsc_traffic_light_get_stop_waypoints(NULL, (tsc_waypoint_list_t *[1]){NULL}), "tsc_traffic_light_get_stop_waypoints");
  expect_null_rejected(tsc_traffic_light_get_group_traffic_lights(NULL, (tsc_traffic_light_list_t *[1]){NULL}), "tsc_traffic_light_get_group_traffic_lights");
  expect_null_rejected(tsc_traffic_manager_get_port(NULL, NULL), "tsc_traffic_manager_get_port");
  expect_null_rejected(tsc_traffic_manager_set_synchronous_mode(NULL, 0), "tsc_traffic_manager_set_synchronous_mode");
  expect_null_rejected(tsc_traffic_manager_set_random_device_seed(NULL, 0), "tsc_traffic_manager_set_random_device_seed");
  expect_null_rejected(tsc_traffic_manager_set_hybrid_physics_mode(NULL, 0), "tsc_traffic_manager_set_hybrid_physics_mode");
  expect_null_rejected(tsc_traffic_manager_set_global_percentage_speed_difference(NULL, NAN), "tsc_traffic_manager_set_global_percentage_speed_difference");
  expect_null_rejected(tsc_traffic_manager_set_global_distance_to_leading_vehicle(NULL, NAN), "tsc_traffic_manager_set_global_distance_to_leading_vehicle");
  expect_null_rejected(tsc_traffic_manager_set_auto_lane_change(NULL, NULL, 0), "tsc_traffic_manager_set_auto_lane_change");
  expect_null_rejected(tsc_traffic_manager_force_lane_change(NULL, NULL, 0), "tsc_traffic_manager_force_lane_change");
  expect_null_rejected(tsc_traffic_manager_set_update_vehicle_lights(NULL, NULL, 0), "tsc_traffic_manager_set_update_vehicle_lights");
  expect_null_rejected(tsc_vehicle_set_autopilot(NULL, 0, 0), "tsc_vehicle_set_autopilot");
  expect_null_rejected(tsc_vehicle_set_light_state(NULL, 0), "tsc_vehicle_set_light_state");
  expect_null_rejected(tsc_vehicle_get_light_state(NULL, NULL), "tsc_vehicle_get_light_state");
  expect_null_rejected(tsc_vehicle_get_speed_limit(NULL, NULL), "tsc_vehicle_get_speed_limit");
  expect_null_rejected(tsc_vehicle_get_traffic_light_state(NULL, NULL), "tsc_vehicle_get_traffic_light_state");
  expect_null_rejected(tsc_vehicle_is_at_traffic_light(NULL, NULL), "tsc_vehicle_is_at_traffic_light");
  expect_null_rejected(tsc_walker_ai_controller_start(NULL), "tsc_walker_ai_controller_start");
  expect_null_rejected(tsc_walker_ai_controller_stop(NULL), "tsc_walker_ai_controller_stop");
  expect_null_rejected(tsc_walker_ai_controller_go_to_location(NULL, NULL), "tsc_walker_ai_controller_go_to_location");
  expect_null_rejected(tsc_walker_ai_controller_set_max_speed(NULL, NAN), "tsc_walker_ai_controller_set_max_speed");
  expect_null_rejected(tsc_waypoint_get_left_lane(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_waypoint_get_left_lane");
  expect_null_rejected(tsc_waypoint_get_right_lane(NULL, (tsc_waypoint_t *[1]){NULL}), "tsc_waypoint_get_right_lane");
  expect_null_rejected(tsc_waypoint_is_rht(NULL, NULL), "tsc_waypoint_is_rht");
  expect_null_rejected(tsc_waypoint_get_left_lane_marking(NULL, NULL, NULL), "tsc_waypoint_get_left_lane_marking");
  expect_null_rejected(tsc_waypoint_get_right_lane_marking(NULL, NULL, NULL), "tsc_waypoint_get_right_lane_marking");
  expect_null_rejected(tsc_waypoint_get_lane_change(NULL, NULL), "tsc_waypoint_get_lane_change");
  expect_null_rejected(tsc_waypoint_get_landmarks(NULL, NAN, 0, (tsc_landmark_list_t *[1]){NULL}), "tsc_waypoint_get_landmarks");
  expect_null_rejected(tsc_waypoint_get_landmarks_of_type(NULL, NAN, NULL, 1, 0, (tsc_landmark_list_t *[1]){NULL}), "tsc_waypoint_get_landmarks_of_type");
  if (g_failures != 0) return 1;
  printf("test_generated: 69 generated functions reject NULL handles\n");
  return 0;
}
