"""Renders the generated code and splices it into the hand-written files."""

from __future__ import annotations

import re
from pathlib import Path

from .spec import ROOT, Function, Spec

HEADER = ROOT / "native" / "include" / "typesafe_carla" / "ffi.h"
CODON_FFI = ROOT / "codon" / "typesafe_carla" / "_ffi.codon"
SHIM = ROOT / "native" / "src" / "generated" / "bindings.cpp"
TEST = ROOT / "tests" / "native" / "test_generated.c"

WIDTH = 100
NOTICE = "Generated by tools/bindgen from the specs in bindings/; do not edit."
REGENERATE = "uv run python -m tools.bindgen generate"


def signature(prefix: str, name: str, params: list[str], end: str) -> str:
    """A declaration wrapped like clang-format: parameters bin-packed and
    aligned after `(`, or on the next line when they do not fit there."""
    one = f"{prefix}{name}({', '.join(params)}){end}"
    if len(one) <= WIDTH:
        return one

    def pack(first: str, indent: str) -> list[str]:
        lines, line = [], first
        for i, p in enumerate(params):
            piece = p + ("," if i < len(params) - 1 else ")" + end)
            if line in (first, indent):
                line += piece
            elif len(line) + 1 + len(piece) > WIDTH:
                lines.append(line)
                line = indent + piece
            else:
                line += " " + piece
        return lines + [line]

    head = f"{prefix}{name}("
    aligned = pack(head, " " * len(head))
    if all(len(line) <= WIDTH for line in aligned):
        return "\n".join(aligned)
    return head + "\n" + "\n".join(pack("    ", "    "))


def header_block(functions: list[Function]) -> list[str]:
    lines: list[str] = []
    for f in functions:
        if f.doc:
            lines.append(f"/* {f.doc} */")
        lines.append(signature(f"TSC_API {f.ret} ", f.name, f.c_params(), ";"))
    return lines


CODON_RESULT = {"tsc_status_t": "i32", "size_t": "int"}


def codon_block(functions: list[Function]) -> list[str]:
    return [f"from C import LIB.{f.name}({', '.join(f.codon_params())}) -> {CODON_RESULT[f.ret]}"
            for f in functions]


def shim(spec: Spec) -> str:
    lines = [f"// {NOTICE}", f"// Regenerate with: {REGENERATE}", '#include "../internal.hpp"', "",
             "using namespace tsc;", "", 'extern "C" {']
    current = None
    for f in spec.generated():
        if f.spec_file != current:
            current = f.spec_file
            lines += ["", f"// bindings/{f.spec_file}" + (f": {f.cpp_class}" if f.cpp_class else "")]
        lines.append("")
        lines.append(signature(f"{f.ret} ", f.name, f.c_params(), " {"))
        if f.ret != "tsc_status_t":  # a list size: plain statements, no error
            lines += [f"  {line}" for line in f.body().split("\n")] + ["}"]
            continue
        if f.out and f.out.type.handle:  # *out is NULL unless the new handle is made
            name = "" if f.out.name == "out" else f', "{f.out.name}"'
            head, tail = f"return new_handle(__func__, {f.out.name}, [&] {{", f"}}{name});"
        else:
            head, tail = "return TSC_GUARD({", "});"
        one = f"  {head} {f.body()} {tail}"
        if len(one) <= WIDTH:
            lines.append(one)
        else:
            lines += [f"  {head}", f"    {f.body()}", f"  {tail}"]
        lines.append("}")
    lines += ["", '}  // extern "C"', ""]
    return "\n".join(lines)


def null_handle_test(spec: Spec) -> str:
    """A C test: every generated function rejects a NULL handle."""
    lines = [f"/* {NOTICE}", " * Every generated function rejects a NULL handle with TSC_INVALID_ARGUMENT",
             " * before looking at its other arguments, which are all invalid here (NULL",
             " * pointers, NaN, out-of-range values). */", '#include "typesafe_carla/ffi.h"', "",
             "#include <math.h>", "#include <stdio.h>", "#include <string.h>", "", "static int g_failures = 0;", "",
             "static void expect_null_rejected(tsc_status_t status, const char *function) {",
             "  if (status != TSC_INVALID_ARGUMENT ||",
             '      strstr(tsc_last_error_message(), "must not be NULL") == NULL) {',
             '    fprintf(stderr, "%s: NULL handle not rejected (status %d: %s)\\n", function, (int)status,',
             "            tsc_last_error_message());", "    ++g_failures;", "  }", "}", "",
             "int main(void) {"]
    for f in spec.generated():
        if f.ret != "tsc_status_t":  # a list size is 0 for a NULL handle
            lines.append(f'  if ({f.name}(NULL) != 0) {{ fputs("{f.name}(NULL)\\n", stderr); '
                         '++g_failures; }')
            continue
        call = ["NULL"] + ["NULL" if a.type.struct or a.type.handle else a.type.invalid
                           for a in f.args]
        if f.out and f.out.type.handle:  # a valid out, so the NULL handle is what fails
            call.append(f"({f.out.type.c} *[1]){{NULL}}")
        elif f.out:
            call.append(f.out.type.invalid if f.out.type.c_param_template else "NULL")
        lines.append(f'  expect_null_rejected({f.name}({", ".join(call)}), "{f.name}");')
    lines += ["  if (g_failures != 0) return 1;",
              f'  printf("test_generated: {len(spec.generated())} generated functions reject NULL handles\\n");',
              "  return 0;", "}", ""]
    return "\n".join(lines)


# Comment delimiters of the files with generated blocks.
COMMENTS = {"c": ("/* ", " */"), "codon": ("# ", "")}


def splice(text: str, style: str, blocks: dict[str, list[Function]], render) -> str:
    """Replaces the body of every generated block; all blocks must be present."""
    open_, close = COMMENTS[style]
    for block, functions in blocks.items():
        begin = f"{open_}BEGIN GENERATED {block} from bindings/{functions[0].spec_file}, do not edit{close}"
        end = f"{open_}END GENERATED {block}{close}"
        for marker in (rf"{re.escape(f'{open_}BEGIN GENERATED {block} ')}.*", re.escape(end)):
            n = len(re.findall(rf"^{marker}$", text, re.MULTILINE))
            if n > 1:
                raise SystemExit(f"generated block {block!r}: a marker occurs {n} times")
        pattern = re.compile(rf"^{re.escape(open_)}BEGIN GENERATED {re.escape(block)} .*?\n(.*?)"
                             rf"^{re.escape(end)}$", re.MULTILINE | re.DOTALL)
        if not pattern.search(text):
            raise SystemExit(f"generated block {block!r} has no markers; add\n  {begin}\n  {end}")
        body = "\n".join(render(functions))
        text = pattern.sub(lambda _: f"{begin}\n{body}\n{end}", text, count=1)
    stale = set(re.findall(r"BEGIN GENERATED (\w+) ", text)) - set(blocks)
    if stale:
        raise SystemExit(f"markers for blocks no longer in the spec: {sorted(stale)}")
    return text


def outputs(spec: Spec) -> dict[Path, str]:
    blocks = spec.blocks()
    return {
        HEADER: splice(HEADER.read_text(), "c", blocks, header_block),
        CODON_FFI: splice(CODON_FFI.read_text(), "codon", blocks, codon_block),
        SHIM: shim(spec),
        TEST: null_handle_test(spec),
    }


def stale(spec: Spec) -> dict[Path, tuple[str, str]]:
    """The generated files that differ from what is on disk: path -> (old, new)."""
    out = {}
    for path, text in outputs(spec).items():
        old = path.read_text() if path.exists() else ""
        if old != text:
            out[path] = (old, text)
    return out
