# Assembles a LibCarla prebuilt prefix (see cmake/LibCarlaPrebuilt.cmake for
# the layout) from a built source tree. Run by the `libcarla_prebuilt` target:
#
#   cmake -DPB_DESC=<build>/libcarla-prebuilt-desc.cmake -P LibCarlaPrebuiltAssemble.cmake
#
# The build tree is not relocatable; the prefix is: it holds copies of the
# static libraries and the headers of every include directory carla-client
# passes on, merged into one include/, and imported targets that refer to them
# relative to the prefix. Two include directories that hold the same header
# with different contents fail the assembly (merging would change which one
# the compiler finds).
cmake_minimum_required(VERSION 3.27.2)

if(NOT PB_DESC)
  message(FATAL_ERROR "usage: cmake -DPB_DESC=<description> -P ${CMAKE_CURRENT_LIST_FILE}")
endif()
include("${PB_DESC}")
string(LENGTH "${PB_CARLA_COMMIT}" _len)
if(NOT PB_CARLA_COMMIT MATCHES "^[0-9a-f]+$" OR NOT _len EQUAL 40)
  message(FATAL_ERROR "LibCarla prebuilt: the CARLA commit is unknown ('${PB_CARLA_COMMIT}'); "
                      "a prebuilt must name the commit it was built from")
endif()

set(_dest "${PB_DEST}")
set(_tmp "${PB_DEST}.tmp")
file(REMOVE_RECURSE "${_tmp}")
file(MAKE_DIRECTORY "${_tmp}/include" "${_tmp}/lib" "${_tmp}/cmake" "${_tmp}/licenses")

foreach(_v PB_COMPILE_DEFINITIONS PB_COMPILE_OPTIONS PB_COMPILE_FEATURES PB_LINK_OPTIONS
           PB_INCLUDE_DIRECTORIES)
  if(${_v} MATCHES "\\$<")
    message(FATAL_ERROR "LibCarla prebuilt: unevaluated generator expression in ${_v}: ${${_v}}")
  endif()
endforeach()

# --- Static libraries --------------------------------------------------------
macro(_pb_name target out)
  if("${target}" STREQUAL "carla-client")
    set(${out} "carla-client")
  else()
    string(REPLACE "::" "_" ${out} "tsc_libcarla::${target}")
  endif()
endmacro()

set(_libnames "")
set(_i 0)
foreach(_t IN LISTS PB_TARGETS)
  if(PB_TYPE_${_i} STREQUAL "STATIC_LIBRARY")
    get_filename_component(_n "${PB_FILE_${_i}}" NAME)
    if(_n IN_LIST _libnames)
      message(FATAL_ERROR "LibCarla prebuilt: two libraries named ${_n}")
    endif()
    list(APPEND _libnames "${_n}")
    file(COPY_FILE "${PB_FILE_${_i}}" "${_tmp}/lib/${_n}")
    set(_lib_${_i} "${_n}")
  endif()
  math(EXPR _i "${_i} + 1")
endforeach()

# Static libraries named by path (FILE:<path> link items).
set(_i 0)
foreach(_t IN LISTS PB_TARGETS)
  foreach(_d IN LISTS PB_DEPS_${_i})
    if(_d MATCHES "^FILE:(.*)$")
      set(_p "${CMAKE_MATCH_1}")
      get_filename_component(_n "${_p}" NAME)
      if(EXISTS "${_tmp}/lib/${_n}")
        file(SHA256 "${_tmp}/lib/${_n}" _a)
        file(SHA256 "${_p}" _b)
        if(NOT _a STREQUAL _b)
          message(FATAL_ERROR "LibCarla prebuilt: two different libraries named ${_n}")
        endif()
      else()
        file(COPY_FILE "${_p}" "${_tmp}/lib/${_n}")
      endif()
    endif()
  endforeach()
  math(EXPR _i "${_i} + 1")
endforeach()

# --- Headers -----------------------------------------------------------------
# A directory named include/ holds only headers (Boost's libs/*/include, ...);
# elsewhere (LibCarla/source, zlib's and libpng's source and build trees) only
# files with a header extension are taken.
set(_hdr_re "\\.(h|hh|hpp|hxx|h\\+\\+|inl|ipp|tcc|inc)$")
set(_nfiles 0)
foreach(_root IN LISTS PB_INCLUDE_DIRECTORIES)
  if(NOT IS_DIRECTORY "${_root}")
    message(FATAL_ERROR "LibCarla prebuilt: include directory ${_root} does not exist")
  endif()
  file(GLOB_RECURSE _files RELATIVE "${_root}" LIST_DIRECTORIES false "${_root}/*")
  list(FILTER _files EXCLUDE REGEX "(^|/)CMakeFiles/")
  get_filename_component(_rootname "${_root}" NAME)
  if(NOT _rootname STREQUAL "include")
    list(FILTER _files INCLUDE REGEX "${_hdr_re}")
  endif()
  foreach(_f IN LISTS _files)
    set(_to "${_tmp}/include/${_f}")
    if(EXISTS "${_to}")
      file(SHA256 "${_to}" _a)
      file(SHA256 "${_root}/${_f}" _b)
      if(NOT _a STREQUAL _b)
        message(FATAL_ERROR "LibCarla prebuilt: include/${_f} differs between include "
                            "directories (${_root} and ${_from_${_a}}); cannot merge them")
      endif()
      continue()
    endif()
    file(SHA256 "${_root}/${_f}" _h)
    set(_from_${_h} "${_root}")
    get_filename_component(_d "${_to}" DIRECTORY)
    file(MAKE_DIRECTORY "${_d}")
    file(COPY_FILE "${_root}/${_f}" "${_to}")
    math(EXPR _nfiles "${_nfiles} + 1")
  endforeach()
endforeach()
list(LENGTH PB_INCLUDE_DIRECTORIES _nroots)
message(STATUS "LibCarla prebuilt: ${_nfiles} headers from ${_nroots} include directories")

# --- Imported targets --------------------------------------------------------
set(_cmake "# Generated by cmake/LibCarlaPrebuiltAssemble.cmake: LibCarla's client library
# (${PB_CARLA_REF} = ${PB_CARLA_COMMIT}) and the static libraries it links, as
# imported targets. Included by cmake/LibCarlaPrebuilt.cmake.
get_filename_component(_tsc_pb_prefix \"\${CMAKE_CURRENT_LIST_DIR}/..\" ABSOLUTE)
")
set(_any_threads OFF)
set(_i 0)
foreach(_t IN LISTS PB_TARGETS)
  if("Threads::Threads" IN_LIST PB_DEPS_${_i})
    set(_any_threads ON)
  endif()
  math(EXPR _i "${_i} + 1")
endforeach()
if(_any_threads)
  string(APPEND _cmake "find_package(Threads REQUIRED)\n")
endif()

set(_i 0)
foreach(_t IN LISTS PB_TARGETS)
  _pb_name("${_t}" _name)
  set(_deps "")
  foreach(_d IN LISTS PB_DEPS_${_i})
    if(_d MATCHES "^FILE:(.*)$")
      get_filename_component(_n "${CMAKE_MATCH_1}" NAME)
      list(APPEND _deps "\${_tsc_pb_prefix}/lib/${_n}")
    elseif(_d IN_LIST PB_TARGETS)
      _pb_name("${_d}" _dn)
      list(APPEND _deps "${_dn}")
    else()
      list(APPEND _deps "${_d}")
    endif()
  endforeach()
  if(PB_TYPE_${_i} STREQUAL "STATIC_LIBRARY")
    string(APPEND _cmake "add_library(${_name} STATIC IMPORTED)
set_target_properties(${_name} PROPERTIES
  IMPORTED_LOCATION \"\${_tsc_pb_prefix}/lib/${_lib_${_i}}\"
  IMPORTED_LINK_INTERFACE_LANGUAGES \"C;CXX\"
  INTERFACE_LINK_LIBRARIES \"${_deps}\")
")
  else()
    string(APPEND _cmake "add_library(${_name} INTERFACE IMPORTED)
set_target_properties(${_name} PROPERTIES INTERFACE_LINK_LIBRARIES \"${_deps}\")
")
  endif()
  math(EXPR _i "${_i} + 1")
endforeach()
# carla-client carries the usage requirements of the whole closure.
string(APPEND _cmake "set_target_properties(carla-client PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES \"\${_tsc_pb_prefix}/include\"
  INTERFACE_COMPILE_DEFINITIONS \"${PB_COMPILE_DEFINITIONS}\"
  INTERFACE_COMPILE_OPTIONS \"${PB_COMPILE_OPTIONS}\"
  INTERFACE_COMPILE_FEATURES \"${PB_COMPILE_FEATURES}\"
  INTERFACE_LINK_OPTIONS \"${PB_LINK_OPTIONS}\")
unset(_tsc_pb_prefix)
")
file(WRITE "${_tmp}/cmake/libcarla-targets.cmake" "${_cmake}")

# --- Licenses ----------------------------------------------------------------
file(COPY_FILE "${PB_LICENSE}" "${_tmp}/licenses/LICENSE.CARLA")
file(COPY_FILE "${PB_NOTICES}" "${_tmp}/licenses/THIRD_PARTY_NOTICES.components")

# --- Manifest ----------------------------------------------------------------
function(_pb_json_str value out)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE _all RELATIVE "${_tmp}" LIST_DIRECTORIES false "${_tmp}/*")
list(SORT _all)
set(_entries "")
foreach(_f IN LISTS _all)
  file(SHA256 "${_tmp}/${_f}" _h)
  _pb_json_str("${_f}" _jf)
  list(APPEND _entries "    ${_jf}: \"${_h}\"")
endforeach()
list(JOIN _entries ",\n" _entries)
string(SHA256 _abi_hash "${PB_ABI}\n")
string(SUBSTRING "${_abi_hash}" 0 12 _abi_hash)
set(_json "{\n")
foreach(_k format carla_repository carla_ref carla_commit carla_version abi abi_hash built_by)
  if(_k STREQUAL "format")
    string(APPEND _json "  \"format\": ${PB_FORMAT},\n")
    continue()
  elseif(_k STREQUAL "abi_hash")
    set(_val "${_abi_hash}")
  else()
    string(TOUPPER "PB_${_k}" _var)
    set(_val "${${_var}}")
  endif()
  _pb_json_str("${_val}" _jv)
  string(APPEND _json "  \"${_k}\": ${_jv},\n")
endforeach()
string(APPEND _json "  \"files\": {\n${_entries}\n  }\n}\n")
file(WRITE "${_tmp}/prebuilt.json" "${_json}")

file(REMOVE_RECURSE "${_dest}")
file(RENAME "${_tmp}" "${_dest}")
list(LENGTH _all _n)
message(STATUS "LibCarla prebuilt: ${_dest} (${_n} files, ABI ${_abi_hash})")
